#Files rendered using apache or CDN, directly accessible via URL
ftpEasyPath=/opt/bitnami/apache-tomcat/webapps/media/
cdnPath=http\://www.lucyjon.com/files/view/

#File are rendered via Javacode,cannot be accessed directly.
ftpControlledPath=/opt/bitnami/apache-tomcat/webapps/media/